name: ADT_CHECKER

on: [push]

jobs:

  check-requirements:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: run-check
          run:  |
              chmod +x ./ci/validate_requirements.sh
              ./ci/validate_requirements.sh
          shell: bash
          env:
            GITHUB_REPO_NAME: ${{ github.event.repository.name }}
  build-and-test:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - name: Setup dotnet
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'
        - name: Install dependencies
          run: dotnet restore
        - name: Build App
          run: dotnet build
        - name: Test with dotnet
          run: dotnet test --no-restore --verbosity normal
